version: "2.2"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    expose: 
      - 8080
    ports:
      - 8080:8080
    command: npm start

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    depends_on:
      - server
    ports:
      - 3000:3000
    command: npm start

  database:
    image: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: exit 0
